version: "3.9"

services:
  ros-core:
    container_name: ros-core
    tty: true
    image: ros:noetic
    command: roscore
    network_mode: "host"
    healthcheck:
      test: ["CMD-SHELL",". /opt/ros/noetic/setup.sh && rostopic list"]
      interval: 1s
      timeout: 2s
      retries: 10
      start_period: 5s

  ros-nodes:
    container_name: ros-nodes
    tty: true
    build: .
    command: roslaunch kwii kwii.launch
    network_mode: "host"
    depends_on:
      ros-core:
        condition: service_healthy

  # output:
  #   build: .
  #   command: rosrun kwii kwii-output.py
  #   network_mode: "host"
  #   depends_on:
  #     ros-core:
  #       condition: service_healthy

  # command:
  #   build: .
  #   command: rosrun kwii kwii_command_node
  #   network_mode: "host"
  #   depends_on:
  #     ros-core:
  #       condition: service_healthy

  # echoer:
  #   image: ros:noetic
  #   command: rostopic echo /commands
  #   network_mode: "host"
  #   depends_on:
  #     ros-core:
  #       condition: service_healthy