version: "3.9"

services:

  ros-nodes:
    container_name: ros-nodes
    tty: true
    build: .
    command: roslaunch kwii kwii.launch
    network_mode: "host"
    environment:
      - DEV_1=${DEV_1}
      - DEV_2=${DEV_2}
    healthcheck:
      test: ["CMD-SHELL",". /opt/ros/noetic/setup.sh && rostopic list"]
      interval: 1s
      timeout: 2s
      retries: 5
      start_period: 3s

  # echoer:
  #   image: ros:noetic-ros-core
  #   command: rostopic echo ${TOPIC}
  #   network_mode: "host"
  #   depends_on:
  #     ros-nodes:
  #       condition: service_healthy